log:
  log_level: info
dns:
  servers:
  - https+local://8.8.8.8/dns-query
inbounds:
- port: 7707
  protocol: trojan
  settings:
    clients:
    - password: 2dd0e430-1650-4915-8377-81f550dff4a9
  stream_settings:
    network: ws
    ws_settings:
      path: 2dd0e430-1650-4915-8377-81f550dff4a9
  sniffing:
    enabled: true
    dest_override:
    - http
    - tls
    - quic
outbounds:
- protocol: freedom
  tag: direct
  settings:
    domain_strategy: UseIPv4
