name: CI

#on:
#  push:
#    branches:
#      - master
#    tags:
#      - v*
#  pull_request:
#    branches:
#      - master

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
      - run: cargo test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - run: |
          mkdir ./artifacts
          mv ./target/x86_64-unknown-linux-musl/release/replit-xray ./artifacts
          tar -czf ./artifacts/replit-xray-musl-64.tar.gz ./artifacts/replit-xray
          pwd
      - uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./artifacts

  release:
    #if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bundle
          path: ./artifacts
      - uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*.tar.gz
