name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  TARGET: x86_64-unknown-linux-musl
  NAME: replit-xray

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: cargo-registry
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --verbose

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ./target
          key: cargo-registry
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: $TARGET
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target $TARGET
      - run: |
          ls -al
          ls -al $TARGET
      - run: |
          mkdir ./artifacts
          mv ./target/$TARGET/release/$NAME ./artifacts
          tar -czf ./artifacts/$NAME-$TARGET.tar.gz ./artifacts/$NAME
          pwd
